Created a container to run every day at a certain hour to refresh the data

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -27,8 +27,8 @@ services:
     restart: unless-stopped
     logging:
       options:
-        max-size: '1m'
-        max-file: '1'
+        max-size: "1m"
+        max-file: "1"
     volumes:
       - ./nginx:/etc/nginx/conf.d
       - ./letsencrypt:/etc/letsencrypt
@@ -54,10 +54,10 @@ services:
 
   planetiler:
     image: ghcr.io/onthegomap/planetiler:latest
+    container_name: planetiler
     volumes:
-      - './tileserver:/output'
+      - "./tileserver:/output"
     command: --force --download --osm_url=https://download.geofabrik.de/europe/portugal-latest.osm.pbf --fetch-wikidata --refresh-sources --free_osm_after_read --output=/output/output.mbtiles
-
   # # # # # # # # # # # # # # # # # # # # #
   # # # # # # # # # # # # # # # # # # # # #
 
@@ -65,4 +65,31 @@ services:
     image: maptiler/tileserver-gl
     restart: unless-stopped
     volumes:
-      - './tileserver:/data'
+      - "./tileserver:/data"
+
+  # # # # # # # # # # # # # # # # # # # # #
+  # # # # # # # # # # # # # # # # # # # # #
+
+  updatebot:
+    image: alpine:latest
+    container_name: updatebot
+    volumes:
+      - /var/run/docker.sock:/var/run/docker.sock
+      - ./docker-compose.yml:/docker-compose.yml
+    command: >
+      sh -c "apk update && apk add --no-cache docker-cli && while true; do
+        if [ $(date +%H:%M) = '02:00' ]; then
+        if docker info > /dev/null 2>&1; then
+          echo 'Updating Data';
+          docker exec planetiler rm -rf /output/* || true;
+          docker restart planetiler;
+        else
+          echo 'Error updating map data;
+        fi;
+        sleep 60;
+      fi;
+      sleep 1;
+      done"
+
+  # # # # # # # # # # # # # # # # # # # # #
+  # # # # # # # # # # # # # # # # # # # # #
